### ISSUE TITLE
Support microDL data IO

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub-sf/iohub#10]
The Zarr reader and writer of `iohub` (formerly `waveorder.io`) has been borrowed in [the Gunpowder-based data workflow of microDL](https://github.com/mehta-lab/microDL/blob/4d164b84ac0696ea33dfcb0ea25cd1326b18fcc1/micro_dl/utils/io_utils.py). We should integrate the adaptations and support further usage being a dependency.

**Comment by ziw-liu** [comment]
The 'Zarr modifier' idea is now implemented in #31.

**Comment by mattersoflight** [comment]
We need to be able to delete or overwrite channels (as in #45 ) when preprocessing data for training.

**Comment by ziw-liu** [comment]
Now tracked in https://github.com/mehta-lab/microDL/pull/209
