### ISSUE TITLE
bump ndtiff version to >1.12.1

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/iohub#124]
`ndtiff==1.12.0` and below have a bug which returned the wrong shape of dask arrays, see https://github.com/micro-manager/NDTiffStorage/pull/107

**Comment by ziw-liu** [comment]
Maybe we can finally get rid of the workaround in this:

https://github.com/czbiohub/iohub/blob/64083d45fa45527a171665c7700f6ad4f9204398/iohub/ndtiff.py#L119-L166

Also this may be related to #105.

**Comment by ieivanov** [comment]
Correct, you shouldn't need to reshape the array at the end anymore.

`ndtiff` now also sorts the axes in PTCZ order when `Dataset.as_array(axes=None)`. Your implementation of axis sorting will error out or omit channels if custom axis names are present.

**Comment by ieivanov** [comment]
Axis sorting is only implemented for the "current" NDTiff format version whereas `mm2.0-20210713_pm0.13.2_2p_3t_2c_7z_1` is `NDTiff_v2_0`, as defined [here](https://github.com/micro-manager/NDTiffStorage/tree/main/python/ndtiff).

Just tested that axes are correctly sorted in PTCZ order for a new pycromanager dataset. We should update the iohub PM test dataset with data from the "current" format.

**Comment by ieivanov** [comment]
P.S. we could extend the `NDTiff_v2_0` format to also do axis sorting. That's something that I had planned on, but didn't get around to implementing.

**Comment by ziw-liu** [comment]
> We should update the iohub PM test dataset with data from the "current" format.

I agree that we should add the new format to tests. However the old one should still be supported to be able to read existing data. Then there will need to be branching logic for different versions like we have for OME-TIFF MMStacks?

**Comment by ieivanov** [comment]
>Does ndtiff provide an API for consistently accessing arrays from different versions?

Yes, the `ndtiff` `Dataset` initializes the right reader such that the returned object has the same API, independent of the underlying dataset version.

**Comment by ziw-liu** [comment]
> Yes, the `ndtiff` `Dataset` initializes the right reader such that the returned object has the same API, independent of the underlying dataset version.

This is what iohub is currently using. However using this method to access arrays from old format datasets still needs reordering axes and reshaping the array (current behavior), while for the new format:

> Your implementation of axis sorting will error out or omit channels if custom axis names are present.

**Comment by ieivanov** [comment]
Just added axis sorting for v2 datasets in micro-manager/NDTiffStorage#117. This way, you can use the same code for v2 or v3 ndtiff datasets. This means that you won't need to do axis sorting in iohub anymore. However, you'll still need to pad the array with singleton dimensions if they are missing in the dataset (as iohub currently does).
