### ISSUE TITLE
Place FOVs in correct HSC row/col upon zarr conversion based on metadata

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/iohub#142]
The mantis acquisition engine generates [metadata](https://github.com/czbiohub/mantis/blob/main/docs/data_structure.md) on which position comes from which well in a 96 well format, currently using a [positions.csv](https://github.com/czbiohub/mantis/blob/main/docs/positions.csv) file. It will be helpful if `iohub convert` can take this file as input and write HCS data in the appropriate rows/columns. I think we can modify the `grid_layout` argument to `TIFFConverter` to be `bool` or `dict` in `{position_index: [row_label, col_label]}` format, e.g. `{0: [A, 1], 1: [A, 1], 2: [A, 2]}`, etc. 

Related issue: https://github.com/micro-manager/pycro-manager/issues/575. The use of a `positions.csv` file is temporary until we can encode the FOV label in the pycromanager metadata. Maybe for now `iohub convert` can take the `positions.csv` file as an input until we can read this information from the metadata.

**Comment by ziw-liu** [comment]
The `positions.csv` file doesn't seem to exist in the data structure example directory of mantis or recent acquisitions. @ieivanov can you provide an example where it's used?

**Comment by ieivanov** [comment]
An example `positions.csv` file is provided here: https://github.com/czbiohub-sf/mantis/blob/main/docs/positions.csv. An example dataset using the `positions.csv` file is: `comp_micro/rawdata/mantis/2023_04_05_mantis_HEK/48wells_1timepoint_4`
