### ISSUE TITLE
Support multiple-MDA (OME-Tiff) datasets

### ISSUE THREAD

**Issue by talonchandler** [czbiohub-sf/iohub#15]
CompMicro and OpenCell teams have workflows that require reading multiple-MDA datasets, so `iohub` support would be extremely valuable. 

Example script for `CompMicro`: https://github.com/mehta-lab/waveorder/pull/96
Example function for `OpenCell`: https://github.com/czbiohub/drug-screen-analysis/blob/master/drug_screen_analysis/functions/reader.py

**Comment by ziw-liu** [comment]
Related: #93.
