### ISSUE TITLE
The MicromanagerOmeTiffReader needs better definitions or documentation for position attributes

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/iohub#152]
The MicromanagerOmeTiffReader provides `positions`, `stage_positions`, `position_arrays`, and `get_num_positions` attributes / methods. We need better definition and/or documentation for these. Some (like `position_arrays`) should probably be internal and others (like `get_num_positions` which returns `self.positions`) should probably be deprecated.

**Comment by ziw-liu** [comment]
We should fix this during the upcoming UAPI refactor of the readers.
