### ISSUE TITLE
iohub cli convert making dtype to np.float64

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub-sf/iohub#167]
I have noticed this with the ndtiffs in mantis datasets 
`/hpc/instruments/cm.mantis/2023_08_03_argolight_resolution/argolight_patterns_7/argolight_patterns_lightsheet_1/`

Where after using iohub  version`0.1.0.dev3`, the conversion returns:

Raw data:
```bash
(pyplay) [eduardo.hirata@cpu-b-1 argolight_patterns_7]$ iohub info -v /hpc/instruments/cm.mantis/2023_08_03_argolight_resolution/argolight_patterns_7/argolight_patterns_lightsheet_1/
Reading file:    /hpc/instruments/cm.mantis/2023_08_03_argolight_resolution/argolight_patterns_7/argolight_patterns_lightsheet_1/
Dataset opened                 
=== Summary ===
Format:          ndtiff
Positions:       1
Time points:     1
Channels:        1
Channel names:   ['GFP EX488 EM525-45']
(Z, Y, X):       (601, 700, 2048)
Z step (um):     0.01
```
Zarr Converted data:

```
iohub info -v argolight_patterns_lightsheet_1.zarr/
Reading file:    argolight_patterns_lightsheet_1.zarr/
Zarr hierarchy:
/
 └── 0
     └── 0
         └── 0
             └── 0 (1, 1, 601, 700, 2048) float64

=== Summary ===
Format:          omezarr v0.4
Axes:            T (time); C (channel); Z (space); Y (space); X (space); 
Channel names:   ['GFP EX488 EM525-45']
Row names:       ['0']
Column names:    ['0']
Wells:           1
```

```

**Comment by ziw-liu** [comment]
What's the NDTiff version in your env?

**Comment by ziw-liu** [comment]
I was able to reproduce with `iohub==0.1.0dev3` and `ndtiff==1.9.0`, but `iohub==0.1.0dev4` and `ndtiff==2.2.1` converts to `uint16` correctly.

**Comment by ziw-liu** [comment]
My intuition is that https://github.com/czbiohub-sf/iohub/pull/145 makes the difference. It may just because ndtiff v1.x does not handle V3 correctly.

**Comment by edyoshikun** [comment]
Most likely need to bump recOrder to depend on `iohub==0.1.0dev4` as this iohub version does convert properly. Closing this issue.
