### ISSUE TITLE
BUG: Test dataset's coordinate transformations do not match data dimension

### ISSUE THREAD

**Issue by talonchandler** [czbiohub-sf/iohub#172]
The test dataset has 4 dimensions, but only has 3 scale transformation. This causes a `RunTimeError` in these lines:

https://github.com/czbiohub-sf/iohub/blob/902bba734969101c50cbddab49bf8d80ec44a01c/iohub/ngff.py#L961-L966

For example: 
```
>>from iohub import open_ome_zarr
>>> dataset = open_ome_zarr("20200812-CardiomyocyteDifferentiation14-Cycle1.zarr")
>>> dataset['B/03/0'].scale
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/mantis-dev/lib/python3.10/site-packages/iohub/ngff.py", line 964, in scale
    raise RuntimeError(
RuntimeError: Length of scale transformation 3 does not match data dimension 4.
```

Based on my reading of the NGFF spec, this seems to be a bug in the test dataset.

**Comment by ziw-liu** [comment]
There is indeed a bug in there. They fixed it recently with v1.2.0. I will update the link in #173.
