### ISSUE TITLE
writing to single OME-zarr store from multiple processes

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub-sf/iohub#20]
We need to be able to read & write a single OME-zarr store or chunked-TIFF store from multiple processes. 

The ND image data supported by iohub is chunked and therefore amenable to multiprocessing. But, metadata is in serial format and it is best to write that from a single thread.  The consensus was that `iohub` should support the creation of an empty dataset to which metadata can be written. Image data can be written afterward.

**Comment by ziw-liu** [comment]
Can this be closed by https://github.com/czbiohub/iohub/pull/87?
