### ISSUE TITLE
TypeError: ImageArray.__init__() got an unexpected keyword argument 'store'

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/iohub#226]
I occasionally get this error when using dask to write to iohub arrays. @ziw-liu I'll try to come up with a reproducible example. Let me know if you happen to know what the problem might be.

**Comment by ziw-liu** [comment]
I'm not sure, but you might want to check your zarr-python version.

**Comment by ziw-liu** [comment]
Oh wait, if you are initializing a `iohub.ngff.ImageArray` it won't work since the `__init__` method only takes one argument.

**Comment by ieivanov** [comment]
Fixed by #262
