### ISSUE TITLE
Error reading MM data from DragonFly

### ISSUE THREAD

**Issue by Soorya19Pradeep** [czbiohub-sf/iohub#240]
The following error message is seen when I try to convert Micromanager data `/hpc/instruments/cm.dragonfly/Dashboard_aim2/2024_08_14_ZIKV_pal17_48h/2024_08_14_ZIKV_pal17_48h_1/` using iohub convert function:

> WARNING:tifffile.tifffile:<tifffile.TiffPage 0 @71365> <tifffile.TiffTag 50839 @71547> invalid value offset 0
> WARNING:tifffile.tifffile:<tifffile.read_micromanager_metadata> failed to read display settings: invalid display_header 0
> WARNING:tifffile.tifffile:<tifffile.TiffPage 0 @71365> <tifffile.TiffTag 50839 @71547> invalid value offset 0
> WARNING:tifffile.tifffile:<tifffile.read_micromanager_metadata> failed to read display settings: invalid display_header 0
> Traceback (most recent call last):
>   File "/hpc/mydata/soorya.pradeep/recOrder/bin/iohub", line 8, in <module>
>     sys.exit(cli())
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/cli/cli.py", line 119, in convert
>     converter.run(check_image=check_image)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/convert.py", line 575, in run
>     self._init_zarr_arrays()
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/convert.py", line 428, in _init_zarr_arrays
>     self._init_hcs_arrays(arr_kwargs)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/convert.py", line 434, in _init_hcs_arrays
>     self._create_zeros_array(row, col, fov, arr_kwargs)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/convert.py", line 450, in _create_zeros_array
>     _ = pos.create_zeros(**arr_kwargs)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/ngff.py", line 715, in create_zeros
>     self._check_shape(shape)
>   File "/hpc/mydata/soorya.pradeep/recOrder/lib/python3.10/site-packages/iohub/ngff.py", line 746, in _check_shape
>     raise ValueError(msg)
> ValueError: Image has 2 channels, while the dataset  has 1.

I can open the images using MicroManager.

**Comment by kfweng0512** [comment]
I also encountered the same warming message when converting my newly generated dataset from Hummingbird. I can open my dataset by using the micromanager as well.

**Comment by ziw-liu** [comment]
@Soorya19Pradeep Is this still an issue? I see that this file has been converted at:

```
/hpc/projects/intracellular_dashboard/viral-sensor/2024_08_14_ZIKV_pal17_48h/0-convert/2024_08_14_ZIKV_pal17_48h.zarr
```

**Comment by ziw-liu** [comment]
Likely due to using an old iohub version without the multicam fixes.
