### ISSUE TITLE
Error for segmentation

### ISSUE THREAD

**Issue by kfweng0512** [czbiohub-sf/iohub#241]
I found this traceback report when I tried to segmenting my virtual stained dataset: Turnout it only generated half of my dataset.

/hpc/mydata/kuo-feng.weng/envs/graphyPy/lib/python3.11/site-packages/cellpose/resnet_torch.py:280: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

```python
 state_dict = torch.load(filename, map_location=torch.device("cpu"))
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 25.3M/25.3M [00:01<00:00, 16.1MB/s]
B/2/0 done
Traceback (most recent call last):
 File "/hpc/projects/group.aviner/KFWENG/Tools/Segmentation/segmentation_script_rev2.py", line 69, in <module>
  data = pos_data.data.numpy()
      ^^^^^^^^^^^^^^^^^^^^^
 File "/hpc/mydata/kuo-feng.weng/envs/graphyPy/lib/python3.11/site-packages/iohub/ngff.py", line 337, in numpy
  return self[:]
      ~~~~^^^
 File "/hpc/mydata/kuo-feng.weng/envs/graphyPy/lib/python3.11/site-packages/zarr/core.py", line 826, in __getitem__
  result = self.get_basic_selection(pure_selection, fields=fields)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/hpc/mydata/kuo-feng.weng/envs/graphyPy/lib/python3.11/site-packages/zarr/core.py", line 952, in get_basic_selection
  return self._get_basic_selection_nd(selection=selection, out=out,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/hpc/mydata/kuo-feng.weng/envs/graphyPy/lib/python3.11/site-packages/zarr/core.py", line 995, in _get_basic_selection_nd
  return self._get_selection(indexer=indexer, out=out, fields=fields)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/hpc/mydata/kuo-feng.weng/envs/graphyPy/lib/python3.11/site-packages/zarr/core.py", line 1274, in _get_selection
  out = np.empty_like(self._meta_array, shape=out_shape,
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 9.14 GiB for an array with shape (46, 2, 13, 2047, 2005) and data type float16
*** Reference count error detected: an attempt was made to deallocate the dtype 23 (e) ***
```

**Comment by ziw-liu** [comment]
@kfweng0512 you likely didn't have enough RAM in the compute node to hold the image array.

**Comment by kfweng0512** [comment]
Thanks ziw-liu. I have tried to set up 16 cores with 26 GB RAM. What change of the setting would you recommend?

**Comment by ziw-liu** [comment]
@kfweng0512 Did you do 26 GB total or 26 GB per core?

**Comment by kfweng0512** [comment]
26G for total. Should I use 26 for each core?

**Comment by ziw-liu** [comment]
@kfweng0512 good to hear that requesting more memory resolved the issue.
