### ISSUE TITLE
Release a pypi version with the pydantic v2 fixes

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub-sf/iohub#243]
@ziw-liu Can we have a alpha release or similar that we can install with the pydantic v2 fixes? 
During the course I found that if we have ultrack, iohub stops working due to the pydantic upgrade.

**Comment by ziw-liu** [comment]
We can tag v0.2.0a1 and push to PyPI.
@JoOkuma Does this sound good to you?

**Comment by edyoshikun** [comment]
I need this pypi alpha release to push this to hugginface since gradio depends on pydantic v2. @ziw-liu I don't think it hurts having an alpha release. Can we make it?

**Comment by JoOkuma** [comment]
@edyoshikun @ziw-liu that works for me

**Comment by ziw-liu** [comment]
@edyoshikun Now available at https://pypi.org/project/iohub/0.2.0a1/. Installing it will currently pull pydantic 2.9.1.

**Comment by edyoshikun** [comment]
Thank you @ziw-liu ~!
