### ISSUE TITLE
Run and check examples on CI

### ISSUE THREAD

**Issue by JoOkuma** [czbiohub-sf/iohub#69]

**Comment by ziw-liu** [comment]
Thanks for noting this. On a longer time scale I think examples should be part of the documentation page, and maybe something like doctest can be used for them.

**Comment by ziw-liu** [comment]
> Thanks for noting this. On a longer time scale I think examples should be part of the documentation page, and maybe something like doctest can be used for them.

Another option is [sphinx-gallery](https://github.com/sphinx-gallery/sphinx-gallery).
