### ISSUE TITLE
Refactor `_set_mm_meta` in `BaseReader` and its children

### ISSUE THREAD

**Issue by JoOkuma** [czbiohub-sf/iohub#85]
This discussion started on #71.

Multiple classes have extremely similar `_set_mm_meta` and other micromanager-related methods that could be simplified and reduce code duplication.

Additionally, why do non-micromanager classes need special micromanager attributes? Shouldn't they live with the rest of the metadata?

**Comment by ziw-liu** [comment]
> Additionally, why do non-micromanager classes need special micromanager attributes? Shouldn't they live with the rest of the metadata?

Can you elaborate on 'the rest of the metadata'? The legacy Zarr reader reads the value from `.zattrs`, which is stored with the rest of the metadata. If you meant the `.metadata` attributes of the v0.4 NGFF node classes, it cannot be since the validation model strictly implements the NGFF spec, which does not have a field for MM metadata.

**Comment by JoOkuma** [comment]
I meant some additional metadata field as [omero](https://ngff.openmicroscopy.org/latest/#omero-md), but for micro-manager, despite not being part of NGFF, it could be an extra field.

From your comment, I understand that the NGFF is strict and doesn't allow any additional fields, is that right?
How is the micro-manager metadata saved on the disk for Zarr?

**Comment by ziw-liu** [comment]
> From your comment, I understand that the NGFF is strict and doesn't allow any additional fields, is that right?

It does allow for additional fields in the `.zattrs` file, which is how MM metadata is being stored now. I meant that metadata classes in the `ngff_meta` module should not implement something that is not declared in the specification.
